[tool.black]
extend-exclude = "venv"         # Ignore the "venv" directory
line-length = 120               # Maximum line length

[tool.django-stubs]
strict_settings = true          # Enable strict type checking for settings.py file

[tool.isort]
force_grid_wrap = 2             # Disable automatic row wrapping
include_trailing_comma = true   # Add a comma after the last element in parentheses
line_length = 120               # Maximum line length (recommended for Black compatibility)
lines_after_imports = 2         # Number of blank lines to leave after imports
multi_line_output = 3           # Use import format with hyphens in parentheses
skip = "venv"                   # Ignore the "venv" directory

[tool.mypy]
ignore_missing_imports = true   # Ignore missing type annotations for external libraries
plugins = [                     # Include the mypy plugins:
    "mypy_django_plugin.main"   # plugin for Django support
]
strict = true                   # Enable strict mode for type checking
